apiVersion: v1
kind: Service
metadata:
  labels:
    app: ack-cube
  name: ack-cube-svc
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ack-cube # 需要与Deployment YAML文件中的matchLabels的值一致。
  type: LoadBalancer