apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ack-cube #应用名称。
  labels:
    app: ack-cube
spec:
  replicas: 2 #设置副本数量。
  selector:
    matchLabels:
      app: ack-cube  #对应服务中Selector的值需要与其一致，才可以通过服务公开此应用。
  template:
    metadata:
      labels:
        app: ack-cube
    spec:
      containers:
      - name: ack-cube
        image: registry.cn-hangzhou.aliyuncs.com/acr-toolkit/ack-cube:1.0 #替换为您实际的镜像地址，格式为：<image_name:tags>。
        ports:
        - containerPort: 80 #需要在服务中暴露该端口。
        resources:
          limits: #设置资源限制。
            cpu: '1'
            memory: 1Gi
          requests: #设置所需资源
            cpu: 500m
            memory: 512Mi        